# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric
minecraft_version=26.1
loader_version=0.19.3
loom_version=1.16.2

# Mod
mod_id=kohs_death_effects
mod_name=KoHs Death Effects
mod_version=1.0.0
maven_group=com.kohs.deatheffects

# Dependencies
fabric_api_version=0.155.2+26.1.2
modmenu_version=18.0.0
