plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

def artifactVersion = "${project.mod_version}+mc${project.minecraft_version}"

version = artifactVersion
group = project.maven_group

base {
	archivesName = project.mod_id
}

repositories {
	mavenCentral()
	maven {
		name = "Terraformers"
		url = "https://maven.terraformersmc.com/releases/"
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"${project.mod_id}" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	modImplementation "com.terraformersmc:modmenu:${project.modmenu_version}"
	implementation include("javazoom:jlayer:1.0.1")
}

def resourceProperties = [
	"version": project.version,
	"mod_id": project.mod_id,
	"mod_name": project.mod_name,
	"minecraft_version": project.minecraft_version
]

processResources {
	inputs.properties resourceProperties

	filesMatching("fabric.mod.json") {
		expand resourceProperties
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

tasks.withType(AbstractArchiveTask).configureEach {
	archiveVersion.set(artifactVersion)
}

tasks.named("jar") {
	from("../../LICENSE") {
		rename { "${project.mod_id}-LICENSE" }
	}
}

tasks.matching { it.name == "sourcesJar" }.configureEach {
	from("../../LICENSE") {
		rename { "${project.mod_id}-LICENSE" }
	}
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
