# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric
minecraft_version=1.21.3
yarn_mappings=1.21.3+build.2
loader_version=0.19.2
loom_version=1.16.1

# Mod
mod_id=kohs_death_effects
mod_name=KoHs Death Effects
mod_version=1.0.0
maven_group=com.kohs.deatheffects

# Dependencies
fabric_api_version=0.114.1+1.21.3
modmenu_version=12.0.1
